# render.yaml
services:
  - type: web
    name: Checkers
    runtime: python
    repo: https://github.com/ashwini-shingote/checkers-app.git
    region: frankfurt
    plan: free
    branch: main
    buildCommand: pipenv install
    startCommand: ./bin/start.sh
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Checkers_DB
          property: connectionString

databases:
  - name: Checkers_DB
    region: frankfurt
    plan: free
    databaseName: app
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
