"""table pieces updated

Revision ID: 0c80c772ead1
Revises: 70d5fe86f8dc
Create Date: 2024-03-17 02:39:21.549502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c80c772ead1'
down_revision: Union[str, None] = '70d5fe86f8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pieces', sa.Column('position', sa.String(), nullable=True))
    op.add_column('pieces', sa.Column('is_out', sa.Boolean(), nullable=True))
    op.drop_column('pieces', 'starting_position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pieces', sa.Column('starting_position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pieces', 'is_out')
    op.drop_column('pieces', 'position')
    # ### end Alembic commands ###
