"""column name updated in table players

Revision ID: 1fa9e9e6f592
Revises: f6610c40f1e4
Create Date: 2024-03-15 20:31:39.283227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa9e9e6f592'
down_revision: Union[str, None] = 'f6610c40f1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('player_name', sa.String(), nullable=True))
    op.drop_index('ix_players_user_name', table_name='players')
    op.create_index(op.f('ix_players_player_name'), 'players', ['player_name'], unique=False)
    op.drop_column('players', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_players_player_name'), table_name='players')
    op.create_index('ix_players_user_name', 'players', ['user_name'], unique=False)
    op.drop_column('players', 'player_name')
    # ### end Alembic commands ###
