"""added  col n relationship in games table

Revision ID: 47e6c6d0b6ee
Revises: a02d0658df7e
Create Date: 2024-03-16 15:15:34.377563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e6c6d0b6ee'
down_revision: Union[str, None] = 'a02d0658df7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
