"""removed col

Revision ID: 70d5fe86f8dc
Revises: 47e6c6d0b6ee
Create Date: 2024-03-16 16:08:59.665447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d5fe86f8dc'
down_revision: Union[str, None] = '47e6c6d0b6ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'winner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('winner', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
