"""added  col in games table

Revision ID: a02d0658df7e
Revises: cc90d9a521d2
Create Date: 2024-03-16 15:05:58.464717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02d0658df7e'
down_revision: Union[str, None] = 'cc90d9a521d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('player1_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('player2_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'players', ['player1_id'], ['id'])
    op.create_foreign_key(None, 'games', 'players', ['player2_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'player2_id')
    op.drop_column('games', 'player1_id')
    # ### end Alembic commands ###
