"""color_id col added in players table

Revision ID: cc90d9a521d2
Revises: decc3aa0f95c
Create Date: 2024-03-16 14:40:43.255773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc90d9a521d2'
down_revision: Union[str, None] = 'decc3aa0f95c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('color_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'color_id')
    # ### end Alembic commands ###
