"""table added pieces, move_type, players

Revision ID: f6610c40f1e4
Revises: 183abd6b93de
Create Date: 2024-03-15 13:01:36.390139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6610c40f1e4'
down_revision: Union[str, None] = '183abd6b93de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_move_types_id'), 'move_types', ['id'], unique=False)
    op.create_table('pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('starting_position', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pieces_id'), 'pieces', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_user_name'), 'players', ['user_name'], unique=False)
    op.add_column('moves', sa.Column('piece_id', sa.Integer(), nullable=True))
    op.add_column('moves', sa.Column('player_id', sa.Integer(), nullable=True))
    op.add_column('moves', sa.Column('move_type_id', sa.Integer(), nullable=True))
    op.add_column('moves', sa.Column('move_order', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'moves', 'move_types', ['move_type_id'], ['id'])
    op.create_foreign_key(None, 'moves', 'players', ['player_id'], ['id'])
    op.create_foreign_key(None, 'moves', 'pieces', ['piece_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moves', type_='foreignkey')
    op.drop_constraint(None, 'moves', type_='foreignkey')
    op.drop_constraint(None, 'moves', type_='foreignkey')
    op.drop_column('moves', 'move_order')
    op.drop_column('moves', 'move_type_id')
    op.drop_column('moves', 'player_id')
    op.drop_column('moves', 'piece_id')
    op.drop_index(op.f('ix_players_user_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_pieces_id'), table_name='pieces')
    op.drop_table('pieces')
    op.drop_index(op.f('ix_move_types_id'), table_name='move_types')
    op.drop_table('move_types')
    # ### end Alembic commands ###
